set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_EXTENSIONS False)
set(CMAKE_EXPORT_COMPILE_COMMANDS True)

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "10.0.0")
    message(FATAL_ERROR "GCC 10 or higher is required")
  endif()
endif()

if(MSVC)
  add_compile_options(/permissive-)

  if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 19.14)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /experimental:external /external:W0 ")
    set(CMAKE_INCLUDE_SYSTEM_FLAG_CXX "/external:I ")
  endif()
else()
  add_compile_options(-pedantic)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  if(MSVC)
    add_compile_options(/W3 /WX)
    # Ignores type conversion warning caused by tileson.hpp
    add_compile_options(/wd4267 /wd4244)
  else()
    add_compile_options(-Wall -Werror)
  endif()
endif()
